FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y -q curl gnupg2
RUN curl http://nginx.org/keys/nginx_signing.key | apt-key add -

RUN apt-get update && \
    apt-get install -y -q nginx

RUN ["nginx", "-v"]

ADD nginx.conf /etc/nginx/
#ADD server.conf /etc/nginx/conf.d
ADD index.html /usr/share/nginx/html

EXPOSE 443 80

CMD ["nginx", "-g", "daemon off;"]