#FROM libmodsec:latest
#FROM ardbegregistry.azurecr.io/modsec:b3ad424694177e8d5e34432f6b7bb6ac97b655a3
FROM ardbegregistry.azurecr.io/libmodsec:latest

RUN apt-get update -y && apt-get install -y libpcre++-dev wget \
    && echo "### Downloading the ModSecurity Nginx-Connector source code" \   
    && git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git \
    ## && cd /usr/src \
    && echo "### Downloading the Nginx source code" \
    ## todo: replace 1.18.0 with ENV
    && wget https://nginx.org/download/nginx-1.18.0.tar.gz \
    && tar -xvzf nginx-1.18.0.tar.gz \
    && echo "### Compiling Nginx source code with ModSec as a dynamic module" \
    && cd nginx-1.18.0 \
    && ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx \
    && make modules \
    && cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules \
    && cd .. \
    && echo "### Configuring ModSecurity" \
    && mkdir /etc/nginx/modsec \
    && wget -P /etc/nginx/modsec/ https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v3/master/modsecurity.conf-recommended \
    && mv /etc/nginx/modsec/modsecurity.conf-recommended /etc/nginx/modsec/modsecurity.conf \
    && cp /usr/src/ModSecurity/unicode.mapping /etc/nginx/modsec \
    && sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/nginx/modsec/modsecurity.conf 
    
ADD nginx.conf /etc/nginx/
ADD server.conf /etc/nginx/conf.d/
ADD modsec.conf /etc/nginx/modsec/main.conf

#COPY configs/nginx.conf /etc/nginx/nginx.conf
#COPY ./configs/modsec.conf /etc/nginx/modsec/main.conf

EXPOSE 443 80

CMD ["nginx", "-g", "daemon off;"]