FROM ubuntu:latest
# FROM debian:latest

RUN apt-get update -y && apt-get install -y \
        git g++ apt-utils autoconf automake build-essential \
        libcurl4-openssl-dev libgeoip-dev liblmdb-dev libpcre2-dev \
        libpcre++-dev libtool libxml2-dev libyajl-dev pkgconf zlib1g-dev \
    && echo "### Download & compile the ModSecurity3 source code" \
    && cd /usr/src \
    && git clone https://github.com/SpiderLabs/ModSecurity.git \
    && cd ModSecurity \
    && echo "## Installing libinjection" \
    ## The libinjection dependency was made part of the ModSecurity project as a gitsubmodule
    && git submodule init && git submodule update \
    && echo "## Configuring Modsecurity" \
    && ./build.sh \
    && ./configure --with-pcre2 \
    && echo "## Compiling Modsecurity" \
    && make \
    && make install 
    #&& echo "### Downloading the Modsecurity Nginx Connector source code" \
    #&& cd /usr/src \   
    #&& git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git \
    #&& echo "### Download & re-compile Nginx source code with the ModSecurity connector" \
    #&& cd /usr/src \
    ## git clone https://github.com/nginx/nginx.git
    #&& wget https://nginx.org/download/nginx-1.22.1.tar.gz \
    #&& tar -xvzf nginx-1.22.1.tar.gz \
    #&& cd nginx-1.22.1 \
    #&& echo "### Compiling the library as a dynamic module" \
    #&& ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx \
    #&& make modules \
    #&& cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules \
    #&& echo "### Configure ModSecurity" \
    #&& mkdir /etc/nginx/modsec \
    #&& wget -P /etc/nginx/modsec/ https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v3/master/modsecurity.conf-recommended \
    #&& mv /etc/nginx/modsec/modsecurity.conf-recommended /etc/nginx/modsec/modsecurity.conf \
    #&& sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/nginx/modsec/modsecurity.conf \
    #&& cp /usr/src/ModSecurity/unicode.mapping /etc/nginx/modsec 

#COPY ./configs/nginx.conf /etc/nginx/nginx.conf
#COPY ./configs/modsec.conf /etc/nginx/modsec/main.conf

CMD service nginx start

EXPOSE 80