on:
  push:
    #paths:
    #  - builds/nginx_base/**

name: Linux_Container_Workflow

jobs:

    basic-tests:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            azcliversion: latest
            inlineScript: |
              az account show

    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: 'Login to registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.ARM_GITHUB_CLIENT_ID}}
            password: ${{ secrets.ARM_GITHUB_CLIENT_SECRET }}
        - name: nginx base image
          run: |
            docker build -f builds/nginx_base/dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-base:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-base:latest
          working-directory: builds/nginx_base
        - name: libmodsec image
          run: |
            docker build -f builds/libmodsec/dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/libmodsec:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/libmodsec:${{ github.sha }}
          working-directory: builds/libmodsec
        - name: nginx waf image
          run: |
            docker build -f builds/nginx_waf/dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-waf:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-waf:latest
          working-directory: builds/nginx_waf

        